name: Run tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install g++12
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt-get update
        sudo apt-get -y install g++-12
    - name: make and run test
      working-directory: src
      run: make CXX=g++-12 test
    - name: make main
      working-directory: src
      run: make CXX=g++-12 main
    - name: make graphics
      working-directory: graphics
      run: make CXX=g++-12
